# Generated by Django 5.1.4 on 2025-01-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_second_user_alter_chatroom_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='second_user',
        ),
    ]
