# Generated by Django 5.1.4 on 2025-01-14 14:00

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_second_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, default='chat/avatars/group/default/group.png', null=True, upload_to=chat.models.chat_group_avatar_path),
        ),
    ]
