# Generated by Django 5.1.4 on 2025-01-14 14:14

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, default='chat/avatars/groups/default/group.png', upload_to=chat.models.chat_group_avatar_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='chat/avatars/users/default/user.png', upload_to=chat.models.user_avatar_path),
        ),
    ]
