# Generated by Django 5.1.4 on 2025-01-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatroom_avatar_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',)},
        ),
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
    ]
