# Generated by Django 5.1.4 on 2025-01-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_profile_options_remove_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='text', max_length=10),
        ),
    ]
