# Generated by Django 5.1.4 on 2025-01-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_message_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
    ]
